% BNF for promptc & PROMPT

VAR_CONS ::= HJSON[ANY] | NIL
VAR_NAME ::= TEXT
VAR_TYPE ::= string | int | float
VAR_DEF  ::= VAR_NAME : VAR_TYPE VAR_CONS

REVERSE_TOKEN ::= {%Q%}
VAR_TOKEN     ::= {TEXT}
TEXT_TOKEN    ::= TEXT
S_TEXT_TOKEN  ::= {{ | }}
SCRIPT_TOKEN  ::= {%TEXT%}
TOKEN         ::= S_TEXT_TOKEN | REVERSE_TOKEN | SCRIPT_TOKEN | VAR_TOKEN | TEXT_TOKEN
TOKENS        ::= TOKEN TOKENS | TOKEN

PROMPT_META  ::= HJSON[ANY]
PROMPT_BLOCK ::= PROMPT_META TOKENS | PROMPT_TOKENS

CONF_ITEM ::= AUTHOR | VERSION | LICENSE | PROJECT | VERSION
CONF_MOD  ::= CONF_ITEM | CONF_ITEM CONF_MOD | NIL

CONF    ::= HJSON[CONF_MOD] | NIL
VARS    ::= VAR_DEF VARS | NIL
PROMPTS ::= PROMPT_BLOCK PROMPTS | NIL

PROMPTC ::= HJSON[CONF, VARS, PROMPTS]
PROMPT  ::= PROMPT_BLOCK